# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('caracteristica', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ramito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ramos.Flor')),
            ],
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('total', models.IntegerField()),
                ('flores', models.ManyToManyField(through='Ramos.Ramito', to='Ramos.Flor')),
            ],
        ),
        migrations.AddField(
            model_name='ramito',
            name='ramo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ramos.Ramo'),
        ),
    ]
